---
name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Determine version
        id: version_id
        run: echo "::set-output name=value::$(git describe --always --tags --dirty)"
      - name: Generate parser
        run: "./gen_parser.sh"
      - name: Build firmware
        uses: espressif/esp-idf-ci-action@release-v4.4
        env:
          PROJECT_NAME: lizard_${{ steps.version_id.outputs.value }}
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: lizard_${{ steps.version_id.outputs.value }}
          tag_name: lizard_${{ steps.version_id.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/*.bin
          asset_name: lizard_${{ steps.version_id.outputs.value }}.bin
          asset_content_type: application/octet-stream

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Build docs
        run: mkdocs build
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: site
